name: EVE-NG Lab CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, windows, eveng]

    defaults:
      run:
        shell: pwsh
        working-directory: .

    env:
      TF_VAR_eveng_host: ${{ secrets.EVE_HOST }}
      TF_VAR_eveng_username: ${{ secrets.EVE_USERNAME }}
      TF_VAR_eveng_password: ${{ secrets.EVE_PASSWORD }}
      TF_INPUT: "false"
      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
