name: EVE-NG Lab CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]
    timeout-minutes: 15

    env:
      TF_VAR_eveng_host: ${{ secrets.EVE_HOST }}
      TF_VAR_eveng_username: ${{ secrets.EVE_USERNAME }}
      TF_VAR_eveng_password: ${{ secrets.EVE_PASSWORD }}
      TF_INPUT: "false"
      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        run: terraform version
        shell: powershell

      - name: Terraform Init
        run: terraform init -no-color
        shell: powershell

      - name: Terraform Validate
        run: terraform validate -no-color
        shell: powershell

      - name: Terraform Plan
        run: terraform plan -input=false -no-color
        shell: powershell
